title: Abdallah Boutrif
description: Games Programmer
site_title: 'Abdallah "Bib" Boutrifs Work'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Bibool
blog_url: https://aboutrif.wixsite.com/portfolio
email: aacboutrif@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg
resume: assets/resume.pdf

# Google Analytics ID
google_analytics: 
